name: Percy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  percy-visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Percy visual tests with Cypress
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}  # Access Percy token from GitHub Secrets
        run: |
          npx percy exec -- npx cypress run